[colors]
background=2a2a2add
text=ffffffff
match=8be9fdff
selection-match=363332ff
selection=7d7d7ddd
selection-text=f8f8f2ff
border=ffffffff

[border]
width=1
radius=0

[dmenu]
# mode=text  # text|index
# exit-immediately-if-empty=no

